// --- League Slug Mapping ---
const teamToLeagueMap = {
    // Premier League
    'manchester-united': { slug: 'premier', name: 'Premier League' },
    'liverpool': { slug: 'premier', name: 'Premier League' },
    'manchester-city': { slug: 'premier', name: 'Premier League' },
    'arsenal': { slug: 'premier', name: 'Premier League' },
    'chelsea': { slug: 'premier', name: 'Premier League' },
    'tottenham': { slug: 'premier', name: 'Premier League' },
    'newcastle': { slug: 'premier', name: 'Premier League' },
    'aston-villa': { slug: 'premier', name: 'Premier League' },
    'west-ham': { slug: 'premier', name: 'Premier League' },
    'brighton': { slug: 'premier', name: 'Premier League' },
    'brentford': { slug: 'premier', name: 'Premier League' },
    'wolves': { slug: 'premier', name: 'Premier League' },
    'everton': { slug: 'premier', name: 'Premier League' },
    'crystal-palace': { slug: 'premier', name: 'Premier League' },
    'fulham': { slug: 'premier', name: 'Premier League' },
    'bournemouth': { slug: 'premier', name: 'Premier League' },
    'leicester-city': { slug: 'premier', name: 'Premier League' },
    'nottingham-forest': { slug: 'premier', name: 'Premier League' },
    'ipswich-town': { slug: 'premier', name: 'Premier League' },
    'southampton': { slug: 'premier', name: 'Premier League' },
  
    // Bundesliga
    'bayern-munich': { slug: 'bundesliga', name: 'Bundesliga' },
    'borussia-dortmund': { slug: 'bundesliga', name: 'Bundesliga' },
    'bayer-leverkusen': { slug: 'bundesliga', name: 'Bundesliga' },
    'rb-leipzig': { slug: 'bundesliga', name: 'Bundesliga' },
    'eintracht-frankfurt': { slug: 'bundesliga', name: 'Bundesliga' },
    'borussia-monchengladbach': { slug: 'bundesliga', name: 'Bundesliga' },
    'union-berlin': { slug: 'bundesliga', name: 'Bundesliga' },
    'vfl-wolfsburg': { slug: 'bundesliga', name: 'Bundesliga' },
    'freiburg': { slug: 'bundesliga', name: 'Bundesliga' },
    'mainz': { slug: 'bundesliga', name: 'Bundesliga' },
    'augsburg': { slug: 'bundesliga', name: 'Bundesliga' },
    'hoffenheim': { slug: 'bundesliga', name: 'Bundesliga' },
    'vfl-bochum': { slug: 'bundesliga', name: 'Bundesliga' },
    'stuttgart': { slug: 'bundesliga', name: 'Bundesliga' },
    'heidenheim': { slug: 'bundesliga', name: 'Bundesliga' },
    'st-pauli': { slug: 'bundesliga', name: 'Bundesliga' },
    'werder-bremen': { slug: 'bundesliga', name: 'Bundesliga' },
    'holstein': { slug: 'bundesliga', name: 'Bundesliga' },
  
    // La Liga
    'barcelona': { slug: 'laliga', name: 'La Liga' },
    'real-madrid': { slug: 'laliga', name: 'La Liga' },
    'atletico-madrid': { slug: 'laliga', name: 'La Liga' },
    'athletic-bilbao': { slug: 'laliga', name: 'La Liga' },
    'sevilla': { slug: 'laliga', name: 'La Liga' },
    'real-sociedad': { slug: 'laliga', name: 'La Liga' },
    'valencia': { slug: 'laliga', name: 'La Liga' },
    'villarreal': { slug: 'laliga', name: 'La Liga' },
    'real-betis': { slug: 'laliga', name: 'La Liga' },
    'celta-vigo': { slug: 'laliga', name: 'La Liga' },
    'getafe': { slug: 'laliga', name: 'La Liga' },
    'osasuna': { slug: 'laliga', name: 'La Liga' },
    'real-mallorca': { slug: 'laliga', name: 'La Liga' },
    'rayo-vallecano': { slug: 'laliga', name: 'La Liga' },
    'espanyol': { slug: 'laliga', name: 'La Liga' },
    'girona': { slug: 'laliga', name: 'La Liga' },
    'alaves': { slug: 'laliga', name: 'La Liga' },
    'las-palmas': { slug: 'laliga', name: 'La Liga' },
    'leganes': { slug: 'laliga', name: 'La Liga' },
    'real-valladolid': { slug: 'laliga', name: 'La Liga' },
  
    // Serie A
    'inter-milan': { slug: 'serie-a', name: 'Serie A' },
    'juventus': { slug: 'serie-a', name: 'Serie A' },
    'ac-milan': { slug: 'serie-a', name: 'Serie A' },
    'napoli': { slug: 'serie-a', name: 'Serie A' },
    'roma': { slug: 'serie-a', name: 'Serie A' },
    'fiorentina': { slug: 'serie-a', name: 'Serie A' },
    'atalanta': { slug: 'serie-a', name: 'Serie A' },
    'lazio': { slug: 'serie-a', name: 'Serie A' },
    'bologna': { slug: 'serie-a', name: 'Serie A' },
    'como': { slug: 'serie-a', name: 'Serie A' },
    'torino': { slug: 'serie-a', name: 'Serie A' },
    'udinese': { slug: 'serie-a', name: 'Serie A' },
    'genoa': { slug: 'serie-a', name: 'Serie A' },
    'cagliari': { slug: 'serie-a', name: 'Serie A' },
    'verona': { slug: 'serie-a', name: 'Serie A' },
    'parma': { slug: 'serie-a', name: 'Serie A' },
    'lecce': { slug: 'serie-a', name: 'Serie A' },
    'venezia': { slug: 'serie-a', name: 'Serie A' },
    'empoli': { slug: 'serie-a', name: 'Serie A' },
    'monza': { slug: 'serie-a', name: 'Serie A' },
  
    // Ligue 1
    'psg': { slug: 'ligue1', name: 'Ligue 1' },
    'olympique-marseille': { slug: 'ligue1', name: 'Ligue 1' },
    'monaco': { slug: 'ligue1', name: 'Ligue 1' },
    'lyon': { slug: 'ligue1', name: 'Ligue 1' },
    'lille': { slug: 'ligue1', name: 'Ligue 1' },
    'nice': { slug: 'ligue1', name: 'Ligue 1' },
    'rennes': { slug: 'ligue1', name: 'Ligue 1' },
    'lens': { slug: 'ligue1', name: 'Ligue 1' },
    'strasbourg': { slug: 'ligue1', name: 'Ligue 1' },
    'reims': { slug: 'ligue1', name: 'Ligue 1' },
    'brest': { slug: 'ligue1', name: 'Ligue 1' },
    'toulouse': { slug: 'ligue1', name: 'Ligue 1' },
    'montpellier': { slug: 'ligue1', name: 'Ligue 1' },
    'nantes': { slug: 'ligue1', name: 'Ligue 1' },
    'le-havre': { slug: 'ligue1', name: 'Ligue 1' },
    'auxerre': { slug: 'ligue1', name: 'Ligue 1' },
    'angers': { slug: 'ligue1', name: 'Ligue 1' },
    'saint-etienne': { slug: 'ligue1', name: 'Ligue 1' },
  
    // Eredivisie
    'ajax': { slug: 'eredivisie', name: 'Eredivisie' },
    'psv-eindhoven': { slug: 'eredivisie', name: 'Eredivisie' },
    'feyenoord': { slug: 'eredivisie', name: 'Eredivisie' },
    'az-alkmaar': { slug: 'eredivisie', name: 'Eredivisie' },
    'fc-twente': { slug: 'eredivisie', name: 'Eredivisie' },
    'fc-utrecht': { slug: 'eredivisie', name: 'Eredivisie' },
    'sc-heerenveen': { slug: 'eredivisie', name: 'Eredivisie' },
    'nec-nijmegen': { slug: 'eredivisie', name: 'Eredivisie' },
    'sparta-rotterdam': { slug: 'eredivisie', name: 'Eredivisie' },
    'go-ahead-eagles': { slug: 'eredivisie', name: 'Eredivisie' },
    'fc-groningen': { slug: 'eredivisie', name: 'Eredivisie' },
    'pec-zwolle': { slug: 'eredivisie', name: 'Eredivisie' },
    'fortuna-sittard': { slug: 'eredivisie', name: 'Eredivisie' },
    'nac-breda': { slug: 'eredivisie', name: 'Eredivisie' },
    'heracles-almelo': { slug: 'eredivisie', name: 'Eredivisie' },
    'willem-ii': { slug: 'eredivisie', name: 'Eredivisie' },
    'almere-city': { slug: 'eredivisie', name: 'Eredivisie' },
    'rkc-waalwijk': { slug: 'eredivisie', name: 'Eredivisie' },
  
    // Liga Portugal
    'sporting-cp': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'sl-benfica': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'fc-porto': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'sc-braga': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'vitoria-guimaraes': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'cd-santa-clara': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'fc-famalicao': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'casa-pia': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'gd-estoril-praia': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'rio-ave': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'moreirense': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'cd-nacional': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'gil-vicente': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'fc-arouca': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'sc-farense': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'cf-estrela-amadora': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'boavista': { slug: 'liga-portugal', name: 'Liga Portugal' },
    'afs': { slug: 'liga-portugal', name: 'Liga Portugal' },
  
    // Super Lig
    'galatasaray': { slug: 'super-lig', name: 'Super Lig' },
    'fenerbahce': { slug: 'super-lig', name: 'Super Lig' },
    'besiktas': { slug: 'super-lig', name: 'Super Lig' },
    'trabzonspor': { slug: 'super-lig', name: 'Super Lig' },
    'istanbul-basaksehir': { slug: 'super-lig', name: 'Super Lig' },
    'kasimpasa': { slug: 'super-lig', name: 'Super Lig' },
    'eyupspor': { slug: 'super-lig', name: 'Super Lig' },
    'goztepe': { slug: 'super-lig', name: 'Super Lig' },
    'bodrum-fk': { slug: 'super-lig', name: 'Super Lig' },
    'samsunspor': { slug: 'super-lig', name: 'Super Lig' },
    'konyaspor': { slug: 'super-lig', name: 'Super Lig' },
    'antalyaspor': { slug: 'super-lig', name: 'Super Lig' },
    'sivasspor': { slug: 'super-lig', name: 'Super Lig' },
    'alanyaspor': { slug: 'super-lig', name: 'Super Lig' },
    'caykur-rizespor': { slug: 'super-lig', name: 'Super Lig' },
    'gaziantep-fk': { slug: 'super-lig', name: 'Super Lig' },
    'kayserispor': { slug: 'super-lig', name: 'Super Lig' },
    'hatayspor': { slug: 'super-lig', name: 'Super Lig' },
    'adana-demirspor': { slug: 'super-lig', name: 'Super Lig' },
  
    // Roshn Saudi League
    'al-hilal': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-nassr': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-ittihad': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-ahli': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-shabab': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-taawoun': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-ettifaq': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-fateh': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-fayha': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'damac': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-wehda': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-raed': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-khaleej': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-riyadh': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-okhdood': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-qadsiah': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-kholood': { slug: 'roshn-saudi', name: 'Roshn Saudi' },
    'al-orobah': { slug: 'roshn-saudi', name: 'Roshn Saudi' }
  };
  module.exports = teamToLeagueMap;
